const GAMES=[
{id:'snake',name:'Snake Recall',desc:'Cresça, faça combos e responda para manter a cobra viva.',icon:'bi-activity',cover:'cover-snake'},
{id:'blocks',name:'Block Rush',desc:'Encaixe blocos e ganhe jogadas especiais ao acertar.',icon:'bi-grid-3x3-gap-fill',cover:'cover-blocks'},
{id:'flap',name:'Flap Recall',desc:'Atravesse os canos e prove que sua memória está afiada.',icon:'bi-twitter',cover:'cover-flap'},
{id:'memory',name:'Memory Match',desc:'Encontre pares enquanto revisa seu deck.',icon:'bi-grid-fill',cover:'cover-flap'},
{id:'runner',name:'Recall Runner',desc:'Corra o máximo possível usando conhecimento como escudo.',icon:'bi-lightning-charge-fill',cover:'cover-blocks'},
{id:'quiz',name:'Quick Quiz',desc:'Rodadas rápidas de perguntas com recompensas em sequência.',icon:'bi-stars',cover:'cover-snake'}];
const $=s=>document.querySelector(s);
function level(xp){return Math.floor(xp/250)+1} function xpNext(xp){return ((level(xp))*250)}
function toast(msg){const host=$('#toastHost');if(!host)return;const el=document.createElement('div');el.className='recall-toast';el.innerHTML=msg;host.appendChild(el);setTimeout(()=>el.remove(),2600)}
function applyTheme(){const s=RecallStore.get();document.documentElement.dataset.theme=s.theme||'dark';const b=$('#themeBtn');if(b)b.innerHTML=s.theme==='dark'?'<i class="bi bi-sun-fill"></i>':'<i class="bi bi-moon-stars-fill"></i>'}
function gameCard(g){return `<article class="game-card"><div class="game-cover ${g.cover}"><i class="bi ${g.icon} game-icon"></i><h3>${g.name}</h3></div><div class="game-body"><p>${g.desc}</p><div class="game-meta"><span><i class="bi bi-lightning-charge-fill"></i> Perguntas integradas</span><a class="play-mini" href="pages/play.html?game=${g.id}">Jogar</a></div></div></article>`}
function deckCard(d){return `<article class="deck-card"><h3>${esc(d.title)}</h3><p>${esc(d.description||'Seu deck personalizado')}</p><div class="deck-foot"><span><i class="bi bi-stack"></i> ${d.cards.length} cards</span><a class="see-all" href="pages/games.html?deck=${encodeURIComponent(d.id)}">Jogar <i class="bi bi-arrow-right"></i></a></div></article>`}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function renderHome(){const s=RecallStore.get();const xpLevel=level(s.xp);$('#totalXp')?.replaceChildren(document.createTextNode(s.xp));$('#totalCoins')?.replaceChildren(document.createTextNode(s.coins));$('#totalStreak')?.replaceChildren(document.createTextNode(`${s.streak} dias`));$('#accuracy')?.replaceChildren(document.createTextNode(s.answered?Math.round(s.correct/s.answered*100)+'%':'0%'));$('#coins')?.replaceChildren(document.createTextNode(s.coins));$('#streak')?.replaceChildren(document.createTextNode(s.streak));$('#sideLevel')?.replaceChildren(document.createTextNode(xpLevel));$('#sideXp')?.replaceChildren(document.createTextNode(`${s.xp} XP`));if($('#sideXpBar'))$('#sideXpBar').style.width=`${Math.min(100,(s.xp%250)/250*100)}%`;if($('#featuredGames'))$('#featuredGames').innerHTML=GAMES.slice(0,3).map(gameCard).join('');if($('#deckPreview'))$('#deckPreview').innerHTML=s.decks.length?s.decks.slice(0,3).map(deckCard).join(''):`<div class="empty"><i class="bi bi-collection fs-2 d-block mb-2"></i>Você ainda não criou nenhum deck.<br><a class="see-all" href="pages/create.html">Criar meu primeiro deck</a></div>`}
document.addEventListener('DOMContentLoaded',()=>{applyTheme();renderHome();$('#themeBtn')?.addEventListener('click',()=>{const s=RecallStore.get();RecallStore.patch({theme:s.theme==='dark'?'light':'dark'});applyTheme()});$('#menuBtn')?.addEventListener('click',()=>$('#sidebar')?.classList.toggle('open'));$('#globalSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter')location.href='pages/decks.html?q='+encodeURIComponent(e.target.value)})});