const params=new URLSearchParams(location.search), game=params.get('game')||'snake', deckId=params.get('deck')||'', wanted=+(params.get('count')||RecallStore.get().settings?.questionsPerGame||5);const canvas=document.querySelector('#gameCanvas'),ctx=canvas.getContext('2d');let state={running:true,score:0,coins:0,qIndex:0,asked:0,questions:[],waiting:false,over:false};
const demo=[{q:'Qual é a capital do Brasil?',a:'Brasília'},{q:'Em que ano ocorreu a Independência do Brasil?',a:'1822'},{q:'Qual é o planeta conhecido como planeta vermelho?',a:'Marte'},{q:'O que a fotossíntese produz?',a:'Glicose e oxigênio'},{q:'Qual é o maior oceano da Terra?',a:'Oceano Pacífico'}];const deck=deckId?RecallStore.getDeck(deckId):null;state.questions=(deck?.cards?.length?deck.cards:demo).sort(()=>Math.random()-.5).slice(0,wanted);
const meta={snake:['Snake Recall','Colete comida, sobreviva e responda para ganhar bônus.'],blocks:['Block Rush','Complete linhas para pontuar; acertos dão blocos especiais.'],flap:['Flap Recall','Clique/toque para voar. Perguntas dão escudos.'],memory:['Memory Match','Combine pares e responda para aumentar a pontuação.'],runner:['Recall Runner','Espaço para pular. Conhecimento dá impulso.'],quiz:['Quick Quiz','Rodadas rápidas. Cada acerto aumenta o multiplicador.']};document.querySelector('#gameName').textContent=meta[game]?.[0]||'RECALL';document.querySelector('#gameHint').textContent=meta[game]?.[1]||'';
function resize(){const max=Math.min(innerWidth-60,760);canvas.style.width=max+'px';canvas.style.height=Math.round(max*520/760)+'px'}addEventListener('resize',resize);resize();
function reward(correct){const xp=correct?25:5,coins=correct?12:2;RecallStore.addXp(xp);RecallStore.addCoins(coins);RecallStore.answer(correct);state.coins+=coins;state.score+=correct?100:20;document.querySelector('#runCoins').textContent=state.coins;document.querySelector('#runScore').textContent=state.score;const pop=document.querySelector('#rewardPop');document.querySelector('#rewardTitle').textContent=correct?'PERFEITO!':'Continue!';document.querySelector('#rewardText').textContent=`+${xp} XP · +${coins} moedas`;pop.classList.add('show');setTimeout(()=>pop.classList.remove('show'),900)}
function normalize(s){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9\s]/g,' ').split(/\s+/).filter(w=>w.length>2&&!['para','como','uma','com','dos','das','que','por','uma','mais','the','and'].includes(w))}
function isEssay(card){return card.q.length>65||card.a.length>90}
function showQuestion(){if(state.qIndex>=state.questions.length){finish();return}state.waiting=true;const card=state.questions[state.qIndex];document.querySelector('#progressText').textContent=`Pergunta ${state.qIndex+1}/${state.questions.length}`;document.querySelector('#questionText').textContent=card.q;document.querySelector('#questionFeedback').textContent='';const answers=document.querySelector('#answers');const essay=document.querySelector('#essayArea');answers.innerHTML='';document.querySelector('#essay').value='';if(isEssay(card)){answers.style.display='none';essay.style.display='block'}else{answers.style.display='grid';essay.style.display='none';const opts=[card.a,...demo.map(x=>x.a).filter(x=>x!==card.a)].sort(()=>Math.random()-.5).slice(0,4);opts.forEach(x=>{const b=document.createElement('button');b.className='answer-btn';b.textContent=x;b.onclick=()=>answer(x===card.a);answers.appendChild(b)})}document.querySelector('#questionModal').classList.add('show')}
function answer(correct){document.querySelector('#questionFeedback').innerHTML=correct?'<span style="color:var(--success);font-weight:800">✓ Resposta correta! Voltando ao jogo...</span>':'<span style="color:var(--danger);font-weight:800">✕ Quase! A resposta era: '+state.questions[state.qIndex].a+'</span>';reward(correct);setTimeout(()=>nextQuestion(),650)}
document.querySelector('#submitEssay').onclick=()=>{const card=state.questions[state.qIndex],expected=normalize(card.a),given=new Set(normalize(document.querySelector('#essay').value));const hits=expected.filter(w=>given.has(w));const threshold=Math.max(2,Math.ceil(Math.min(expected.length,8)*.35));answer(hits.length>=threshold)};
function nextQuestion(){state.qIndex++;state.asked++;document.querySelector('#questionModal').classList.remove('show');state.waiting=false;if(!state.over&&state.qIndex<state.questions.length)setTimeout(()=>{if(state.score>0||state.qIndex===0)showQuestion()},900)}
function finish(){state.over=true;state.running=false;document.querySelector('#questionText').textContent='Partida concluída!';document.querySelector('#answers').style.display='none';document.querySelector('#essayArea').style.display='none';document.querySelector('#questionFeedback').innerHTML=`<b>🏆 ${state.score} pontos</b><br>Você respondeu ${state.questions.length} perguntas e ganhou ${state.coins} moedas.`;document.querySelector('#questionModal').classList.add('show')}
// --- tiny arcade engines ---
let keys={},last=0,frame=0,snake={x:12,y:10,dir:{x:1,y:0},body:[],food:{x:5,y:5}},flap={x:150,y:250,vy:0,pipes:[]},blocks={grid:Array.from({length:10},()=>Array(8).fill(0)),x:2,y:2};addEventListener('keydown',e=>{keys[e.key]=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();if(game==='snake'){if(e.key==='ArrowUp'&&snake.dir.y===0)snake.dir={x:0,y:-1};if(e.key==='ArrowDown'&&snake.dir.y===0)snake.dir={x:0,y:1};if(e.key==='ArrowLeft'&&snake.dir.x===0)snake.dir={x:-1,y:0};if(e.key==='ArrowRight'&&snake.dir.x===0)snake.dir={x:1,y:0}}if(game==='flap'&&e.key===' ')flap.vy=-6});addEventListener('keyup',e=>keys[e.key]=false);canvas.addEventListener('pointerdown',()=>{if(game==='flap')flap.vy=-6});
function bg(){ctx.fillStyle='#0b0d16';ctx.fillRect(0,0,760,520);ctx.strokeStyle='#ffffff08';for(let x=0;x<760;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,520);ctx.stroke()}for(let y=0;y<520;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(760,y);ctx.stroke()}}
function drawSnake(t){bg();const size=26;if(!snake.body.length)snake.body=[{x:12,y:10},{x:11,y:10},{x:10,y:10}];if(t-(drawSnake.last||0)>125&&!state.waiting){snake.x+=snake.dir.x;snake.y+=snake.dir.y;snake.body.unshift({x:snake.x,y:snake.y});if(snake.x===snake.food.x&&snake.y===snake.food.y){state.score+=10;snake.food={x:Math.floor(Math.random()*28),y:Math.floor(Math.random()*18)}}else snake.body.pop();if(snake.x<0||snake.x>=29||snake.y<0||snake.y>=19||snake.body.slice(1).some(p=>p.x===snake.x&&p.y===snake.y)){snake={x:12,y:10,dir:{x:1,y:0},body:[],food:{x:5,y:5}};if(!state.waiting)showQuestion()}drawSnake.last=t}snake.body.forEach((p,i)=>{ctx.fillStyle=i?'#37d89c':'#a8f7d6';ctx.beginPath();ctx.roundRect(p.x*size+3,p.y*size+3,size-6,size-6,7);ctx.fill()});ctx.fillStyle='#f4ba42';ctx.beginPath();ctx.arc(snake.food.x*size+13,snake.food.y*size+13,9,0,7);ctx.fill();}
function drawFlap(t){bg();flap.vy+=.25;flap.y+=flap.vy;if(!state.waiting&&t-(drawFlap.last||0)>150){flap.pipes.push({x:760,gap:150+Math.random()*170});drawFlap.last=t}flap.pipes.forEach(p=>p.x-=2.5);flap.pipes=flap.pipes.filter(p=>p.x>-70);ctx.fillStyle='#56d2c6';ctx.beginPath();ctx.arc(flap.x,flap.y,18,0,7);ctx.fill();flap.pipes.forEach(p=>{ctx.fillStyle='#5b7cf7';const top=p.gap-75,bottom=p.gap+75;ctx.fillRect(p.x,0,55,top);ctx.fillRect(p.x,bottom,55,520-bottom);if(flap.x>p.x&&flap.x<p.x+55&&(flap.y<top||flap.y>bottom)){flap={x:150,y:250,vy:0,pipes:[]};if(!state.waiting)showQuestion()}});if(flap.y<0||flap.y>520){flap={x:150,y:250,vy:0,pipes:[]};if(!state.waiting)showQuestion()}}
function drawBlocks(t){bg();const s=46,ox=190,oy=30;for(let y=0;y<10;y++)for(let x=0;x<8;x++){ctx.strokeStyle='#ffffff12';ctx.strokeRect(ox+x*s,oy+y*s,s-3,s-3);if(blocks.grid[y][x]){ctx.fillStyle=['#6a5cf6','#ef5d83','#3fc6a1','#f3b63f'][blocks.grid[y][x]-1];ctx.fillRect(ox+x*s+4,oy+y*s+4,s-11,s-11)}}if(!state.waiting&&t-(drawBlocks.last||0)>1000){const y=Math.floor(Math.random()*10),x=Math.floor(Math.random()*8);blocks.grid[y][x]=Math.floor(Math.random()*4)+1;for(let yy=0;yy<10;yy++)if(blocks.grid[yy].every(Boolean)){blocks.grid[yy].fill(0);state.score+=50;showQuestion();break}drawBlocks.last=t}}
function drawQuick(){bg();ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='900 54px system-ui';ctx.fillText('⚡ QUICK QUIZ',380,240);ctx.font='700 18px system-ui';ctx.fillStyle='#9a9db2';ctx.fillText('Acerte para ganhar XP, moedas e combo.',380,280)}
function loop(t){if(!state.over){if(game==='snake')drawSnake(t);else if(game==='flap')drawFlap(t);else if(game==='blocks')drawBlocks(t);else drawQuick();if(!state.waiting&&state.qIndex<state.questions.length&&t-(loop.last||0)>12000){showQuestion();loop.last=t}else loop.last=t}requestAnimationFrame(loop)}
loop(0);setTimeout(showQuestion,1800);document.querySelector('#pauseBtn').onclick=()=>{state.running=!state.running;document.querySelector('#pauseBtn').textContent=state.running?'Pausar':'Continuar';if(state.running)requestAnimationFrame(loop)};